/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BodyPage: typeof import('./src/components/bodyPage.vue')['default']
    ContentPage: typeof import('./src/components/contentPage.vue')['default']
    FooterPage: typeof import('./src/components/footerPage.vue')['default']
    HeaderMenu: typeof import('./src/components/headerMenu.vue')['default']
    IMaterialSymbolsCalendarMonth: typeof import('~icons/material-symbols/calendar-month')['default']
    IMaterialSymbolsFileMap: typeof import('~icons/material-symbols/file-map')['default']
    ITablerClockHour5: typeof import('~icons/tabler/clock-hour5')['default']
    LocationEvent: typeof import('./src/components/locationEvent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamContent: typeof import('./src/components/teamContent.vue')['default']
  }
}
