/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutEvent: typeof import('./src/components/aboutEvent.vue')['default']
    BodyPage: typeof import('./src/components/bodyPage.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardsInfoMember: typeof import('./src/components/cardsInfoMember.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ContentPage: typeof import('./src/components/contentPage.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DrawerMembersSaved: typeof import('./src/components/drawerMembersSaved.vue')['default']
    EventTime: typeof import('./src/components/eventTime.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FooterPage: typeof import('./src/components/footerPage.vue')['default']
    FormItem: typeof import('./src/components/formItem.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeadContent: typeof import('./src/components/headContent.vue')['default']
    HeaderMenu: typeof import('./src/components/headerMenu.vue')['default']
    IIcBaselineFacebook: typeof import('~icons/ic/baseline-facebook')['default']
    IIcBaselinePayments: typeof import('~icons/ic/baseline-payments')['default']
    ILineiconsInstagramOriginal: typeof import('~icons/lineicons/instagram-original')['default']
    IMaterialSymbolsCalendarMonth: typeof import('~icons/material-symbols/calendar-month')['default']
    IMaterialSymbolsCalendarMonthOutlineRounded: typeof import('~icons/material-symbols/calendar-month-outline-rounded')['default']
    IMaterialSymbolsCall: typeof import('~icons/material-symbols/call')['default']
    IMaterialSymbolsChurchRounded: typeof import('~icons/material-symbols/church-rounded')['default']
    IMaterialSymbolsDatabaseSearch: typeof import('~icons/material-symbols/database-search')['default']
    IMaterialSymbolsDeleteOutlineRounded: typeof import('~icons/material-symbols/delete-outline-rounded')['default']
    IMaterialSymbolsFemaleRounded: typeof import('~icons/material-symbols/female-rounded')['default']
    IMaterialSymbolsFileMap: typeof import('~icons/material-symbols/file-map')['default']
    IMaterialSymbolsIdCardOutlineRounded: typeof import('~icons/material-symbols/id-card-outline-rounded')['default']
    IMaterialSymbolsListAltAdd: typeof import('~icons/material-symbols/list-alt-add')['default']
    IMaterialSymbolsListAltCheck: typeof import('~icons/material-symbols/list-alt-check')['default']
    IMaterialSymbolsMaleRounded: typeof import('~icons/material-symbols/male-rounded')['default']
    IMaterialSymbolsSyncSavedLocally: typeof import('~icons/material-symbols/sync-saved-locally')['default']
    IMaterialSymbolsTabClose: typeof import('~icons/material-symbols/tab-close')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ITablerClockHour5: typeof import('~icons/tabler/clock-hour5')['default']
    LocationEvent: typeof import('./src/components/locationEvent.vue')['default']
    PayEventView: typeof import('./src/components/payEventView.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RegisterMembers: typeof import('./src/components/registerMembers.vue')['default']
    RegistersCard: typeof import('./src/components/registersCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    TeamContent: typeof import('./src/components/teamContent.vue')['default']
    TimerToEvent: typeof import('./src/components/timerToEvent.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ViewPaymentMethods: typeof import('./src/components/viewPaymentMethods.vue')['default']
  }
  export interface ComponentCustomProperties {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
